---
abstract: 'SagePay (formerly Protx) backend for Business::OnlinePayment'
author:
  - 'Simon Elliott <cpan@papercreatures.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300001, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-SagePay
requires:
  Business::OnlinePayment: 2.01
  Data::Dumper: 0
  Devel::Dwarn: 0
  Net::SSLeay: 1.35
  Test::More: 0
resources:
  bugtracker: https://github.com/purge/Business-OnlinePayment-SagePay/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/purge/Business-OnlinePayment-SagePay
version: 0.14
